#!/usr/bin/env bash
# Regenerates the transparent twin and populated picker preview of the home widget layout:
#   widget_material.xml -> widget_material_shadow.xml (WidgetMaterialHeader -> ...HeaderShadow)
# RemoteViews cannot change a TextView's shadow at runtime, so each twin swaps the text styles
# for ones that add a shadow.
set -euo pipefail
LAYOUT="$(cd "$(dirname "$0")/.." && pwd)/app/src/main/res/layout"

twin() {
  local source="$1" target="$2" from="$3" to="$4"
  {
    printf '<?xml version="1.0" encoding="utf-8"?>\n'
    printf '<!-- GENERATED by android/tools/widget-card-shadow.sh from %s. Do not edit. -->\n' \
      "$source"
    sed -e '1d' -e "s|@style/${from}\\.|@style/${to}.|g" "$LAYOUT/$source"
  } > "$LAYOUT/$target"
}

twin widget_material.xml widget_material_shadow.xml WidgetMaterialHeader WidgetMaterialHeaderShadow

# The picker inflates XML without running MaterialCardRenderer or loading account data.
python3 - "$LAYOUT" <<'PY'
from pathlib import Path
import re
import sys
import xml.etree.ElementTree as ET

layouts = Path(sys.argv[1])
android = "{http://schemas.android.com/apk/res/android}"
tools = "{http://schemas.android.com/tools}"
ET.register_namespace("android", android[1:-1])
ET.register_namespace("tools", tools[1:-1])
root = ET.parse(layouts / "widget_material.xml").getroot()
# Widget hosts inflate framework ImageView; AppCompat's app:tint is not available.
root.set(tools + "ignore", "UseAppTint")
renderer = layouts.parents[1] / "java/me/pipi/codexmeter/MaterialCardRenderer.java"
renderer_source = renderer.read_text()

def metric(name):
    return float(re.search(rf"{name} = ([\d.]+)f", renderer_source).group(1))

scale = metric("MIN_SCALE")
text_scale = metric("TEXT_REFERENCE_SCALE")
elements = {element.get(android + "id", "").split("/")[-1]: element
            for element in root.iter()}

for element in root.iter():
    for attribute, value in list(element.attrib.items()):
        if re.fullmatch(r"[\d.]+dp", value):
            element.set(attribute, f"{float(value[:-2]) * scale:g}dp")
    if element.tag == "TextView":
        element.set(android + "textColor", "@color/widget_material_text")

def set_attrs(identifier, **attributes):
    for name, value in attributes.items():
        elements[identifier].set(android + name, value)

set_attrs("md_surface", tint="@color/widget_material_surface")
set_attrs("md_logo", tint="@color/widget_material_accent")
set_attrs("md_refresh", tint="@color/widget_material_text")
refresh_shift = metric("ICON") * scale * metric("REFRESH_END_INSET")
set_attrs("md_refresh", paddingStart=f"{refresh_shift:g}dp",
          paddingEnd=f"{-refresh_shift:g}dp", layout_marginStart=f"{metric('HEADER_SPACING'):g}dp")
set_attrs("md_header", layout_marginStart="0dp")
set_attrs("md_title", text="@string/widget_preview_plan",
          textSize=f"{metric('VALUE_TEXT') * text_scale:g}dp",
          layout_marginStart=f"{metric('HEADER_SPACING'):g}dp")
set_attrs("md_status", visibility="invisible")
set_attrs("md_updated", textSize=f"{metric('UPDATED_TEXT'):g}sp", fontFamily="sans-serif-medium")
for slot in (1, 3):
    set_attrs(f"md_panel_{slot}", visibility="gone")
for slot, window in ((0, "five_hour"), (2, "weekly")):
    set_attrs(f"md_panel_bg_{slot}", tint="@color/widget_material_panel")
    set_attrs(f"md_name_{slot}", text=f"@string/widget_card_{window}",
              textSize=f"{metric('NAME_TEXT') * text_scale:g}dp")
    set_attrs(f"md_value_{slot}", text=f"@string/widget_preview_{window}_value",
              textSize=f"{metric('VALUE_TEXT') * text_scale:g}dp")
    set_attrs(f"md_bar_{slot}", layout_marginTop=f"{metric('PANEL_GAP'):g}dp")
    set_attrs(f"md_detail_{slot}", layout_marginTop=f"{metric('PANEL_GAP'):g}dp")
    set_attrs(f"md_track_{slot}", tint="@color/widget_material_track")
    set_attrs(f"md_fill_{slot}", tint="@color/widget_material_fill",
              src=f"@drawable/widget_preview_{window}_fill")
    set_attrs(f"md_reset_{slot}", text=f"@string/widget_preview_{window}_reset",
              textSize=f"{metric('DETAIL_TEXT') * text_scale:g}dp",
              textColor="@color/widget_material_secondary")

ET.indent(root, space="    ")
output = ('<?xml version="1.0" encoding="utf-8"?>\n'
          '<!-- GENERATED by android/tools/widget-card-shadow.sh from widget_material.xml. '
          'Synthetic picker data only. Do not edit. -->\n')
(layouts / "widget_material_preview.xml").write_text(output + ET.tostring(root, encoding="unicode") + "\n")

# Preserve the current generic provider contract while hiding only the ColorOS picker entry.
providers = layouts.parent / "xml-v31"
dial = (providers / "codex_dial_widget_info.xml").read_text()
def hidden_features(match):
    features = match.group(1).split("|")
    if "hide_from_picker" not in features:
        features.append("hide_from_picker")
    return 'android:widgetFeatures="' + "|".join(filter(None, features)) + '"'

dial, count = re.subn(r'android:widgetFeatures="([^"]*)"', hidden_features, dial)
assert count == 1, "The generic dial provider must declare widgetFeatures once"
declaration, body = dial.split("\n", 1)
provider_header = ('<!-- GENERATED by android/tools/widget-card-shadow.sh from '
                   'codex_dial_widget_info.xml. Do not edit. -->\n')
(providers / "codex_dial_widget_hidden_info.xml").write_text(
    declaration + "\n" + provider_header + body)
PY
