#!/usr/bin/env bash
# Regenerates the transparent twin and populated picker preview of the home widget layout:
#   widget_material.xml -> widget_material_shadow.xml (WidgetMaterialHeader -> ...HeaderShadow)
# RemoteViews cannot change a TextView's shadow at runtime, so each twin swaps the text styles
# for ones that add a shadow.
set -euo pipefail
LAYOUT="$(cd "$(dirname "$0")/.." && pwd)/app/src/main/res/layout"

twin() {
  local source="$1" target="$2" from="$3" to="$4"
  {
    printf '<?xml version="1.0" encoding="utf-8"?>\n'
    printf '<!-- GENERATED by android/tools/widget-card-shadow.sh from %s. Do not edit. -->\n' \
      "$source"
    sed -e '1d' -e "s|@style/${from}\\.|@style/${to}.|g" "$LAYOUT/$source"
  } > "$LAYOUT/$target"
}

twin widget_material.xml widget_material_shadow.xml WidgetMaterialHeader WidgetMaterialHeaderShadow

# The picker inflates XML without running MaterialCardRenderer or loading account data.
python3 - "$LAYOUT" <<'PY'
from pathlib import Path
import copy
import re
import sys
import xml.etree.ElementTree as ET

layouts = Path(sys.argv[1])
android = "{http://schemas.android.com/apk/res/android}"
tools = "{http://schemas.android.com/tools}"
ET.register_namespace("android", android[1:-1])
ET.register_namespace("tools", tools[1:-1])
root = ET.parse(layouts / "widget_material.xml").getroot()
# Widget hosts inflate framework ImageView; AppCompat's app:tint is not available.
root.set(tools + "ignore", "UseAppTint")
renderer = layouts.parents[1] / "java/me/pipi/codexmeter/MaterialCardRenderer.java"
renderer_source = renderer.read_text()

def metric(name):
    return float(re.search(rf"{name} = ([\d.]+)f", renderer_source).group(1))

scale = metric("MIN_SCALE")
text_scale = metric("TEXT_REFERENCE_SCALE")
elements = {element.get(android + "id", "").split("/")[-1]: element
            for element in root.iter()}

for element in root.iter():
    for attribute, value in list(element.attrib.items()):
        if re.fullmatch(r"[\d.]+dp", value):
            element.set(attribute, f"{float(value[:-2]) * scale:g}dp")
    if element.tag == "TextView":
        element.set(android + "textColor", "@color/widget_material_text")

def set_attrs(identifier, **attributes):
    for name, value in attributes.items():
        elements[identifier].set(android + name, value)

set_attrs("md_surface", tint="@color/widget_material_surface")
set_attrs("md_logo", tint="@color/widget_material_accent")
set_attrs("md_refresh", tint="@color/widget_material_text")
refresh_shift = metric("ICON") * scale * metric("REFRESH_END_INSET")
set_attrs("md_refresh", paddingStart=f"{refresh_shift:g}dp",
          paddingEnd=f"{-refresh_shift:g}dp", layout_marginStart=f"{metric('HEADER_SPACING'):g}dp")
set_attrs("md_header", layout_marginStart="0dp")
set_attrs("md_title", text="@string/widget_preview_plan",
          textSize=f"{metric('VALUE_TEXT') * text_scale:g}dp",
          layout_marginStart=f"{metric('HEADER_SPACING'):g}dp")
set_attrs("md_status", visibility="invisible")
set_attrs("md_updated", textSize=f"{metric('UPDATED_TEXT'):g}sp", fontFamily="sans-serif-medium")
for slot in (1, 3):
    set_attrs(f"md_panel_{slot}", visibility="gone")
for slot, window in ((0, "five_hour"), (2, "weekly")):
    set_attrs(f"md_panel_bg_{slot}", tint="@color/widget_material_panel")
    set_attrs(f"md_name_{slot}", text=f"@string/widget_card_{window}",
              textSize=f"{metric('NAME_TEXT') * text_scale:g}dp")
    set_attrs(f"md_value_{slot}", text=f"@string/widget_preview_{window}_value",
              textSize=f"{metric('VALUE_TEXT') * text_scale:g}dp")
    set_attrs(f"md_bar_{slot}", layout_marginTop=f"{metric('PANEL_GAP'):g}dp")
    set_attrs(f"md_detail_{slot}", layout_marginTop=f"{metric('PANEL_GAP'):g}dp")
    # XML tint otherwise defaults to SRC_ATOP and discards the translucent track alpha.
    set_attrs(f"md_track_{slot}", tint="@color/widget_material_track", tintMode="src_in")
    set_attrs(f"md_fill_{slot}", tint="@color/widget_material_fill",
              src=f"@drawable/widget_preview_{window}_fill")
    set_attrs(f"md_reset_{slot}", text=f"@string/widget_preview_{window}_reset",
              textSize=f"{metric('DETAIL_TEXT') * text_scale:g}dp",
              textColor="@color/widget_material_secondary")

ET.indent(root, space="    ")
output = ('<?xml version="1.0" encoding="utf-8"?>\n'
          '<!-- GENERATED by android/tools/widget-card-shadow.sh from widget_material.xml. '
          'Synthetic picker data only. Do not edit. -->\n')
(layouts / "widget_material_preview.xml").write_text(output + ET.tostring(root, encoding="unicode") + "\n")

def classic_card(preview):
    nodes = {element.get(android + "id", "").split("/")[-1]: element
             for element in preview.iter()}
    nodes["md_surface"].set(android + "tint", "@color/widget_oneui_surface")
    nodes["md_logo"].set(android + "src", "@drawable/ic_codex_logo_color")
    nodes["md_logo"].attrib.pop(android + "tint", None)
    for slot, window in ((0, "five_hour"), (2, "weekly")):
        nodes[f"md_panel_bg_{slot}"].set(android + "tint", "@color/widget_oneui_panel")
        nodes[f"md_fill_{slot}"].set(android + "src", f"@drawable/widget_classic_preview_{window}_fill")
        nodes[f"md_fill_{slot}"].attrib.pop(android + "tint", None)
    return nodes

# Static sample windows use 36% and 58%; both share the common normal green gradient.
for window, level in (("five_hour", "6400"), ("weekly", "4200")):
    fill = ET.parse(layouts.parent / "drawable/widget_classic_capsule_fill.xml").getroot()
    fill.set(android + "level", level)
    ET.indent(fill, space="    ")
    (layouts.parent / f"drawable/widget_classic_preview_{window}_fill.xml").write_text(
        output.replace("widget_material.xml", "widget_classic_capsule_fill.xml")
        + ET.tostring(fill, encoding="unicode") + "\n")

# Samsung's size-specific preview contract is 125x130dp, not the provider's desktop minimum.
# Keep the common card content and height-based typography, scaled for this thumbnail.
samsung_card = copy.deepcopy(root)
samsung_card.set(android + "layout_width", "125dp")
samsung_card.set(android + "layout_height", "130dp")
samsung_card.set(android + "background", "@color/widget_oneui_surface")
nodes = classic_card(samsung_card)
nodes["md_surface"].set(android + "visibility", "gone")
preview_text_scale = max(metric("MIN_SCALE"), min(metric("MAX_SCALE"),
    metric("TEXT_REFERENCE_SCALE") * 130 / metric("TEXT_REFERENCE_HEIGHT")))
nodes["md_title"].set(android + "textSize", f"{metric('VALUE_TEXT') * preview_text_scale:g}dp")
for slot in (0, 2):
    for part, font in (("name", "NAME_TEXT"), ("value", "VALUE_TEXT"), ("reset", "DETAIL_TEXT")):
        nodes[f"md_{part}_{slot}"].set(android + "textSize", f"{metric(font) * preview_text_scale:g}dp")
    for part in ("bar", "detail"):
        nodes[f"md_{part}_{slot}"].set(android + "layout_marginTop", f"{metric('PANEL_GAP') * scale:g}dp")
ET.indent(samsung_card, space="    ")
(layouts / "widget_oneui_card_preview.xml").write_text(
    output + ET.tostring(samsung_card, encoding="unicode") + "\n")

# ColorOS measures generated previews without constraints and never enlarges them.
# Match Calendar's 146dp square preview without changing the placed-widget contract.
classic_card(root)
root.set(android + "minWidth", "146dp")
root.set(android + "minHeight", "146dp")
(layouts / "widget_coloros_card_preview.xml").write_text(
    output + ET.tostring(root, encoding="unicode") + "\n")

# Populate the common One UI dial layout at Samsung's 125x52dp Small preview size.
# Its padding, arc, icon and value geometry follow OneUiWidgetAppearance.sizeDial.
dial_root = ET.parse(layouts / "widget_oneui_rings.xml").getroot()
dial_root.set(android + "layout_width", "125dp")
dial_root.set(android + "layout_height", "52dp")
dial_root.set(android + "background", "@color/widget_oneui_surface")
dial_nodes = {element.get(android + "id", "").split("/")[-1]: element
              for element in dial_root.iter()}
dial_nodes["dial_surface"].set(android + "visibility", "gone")
appearance = (renderer.parent / "OneUiWidgetAppearance.java").read_text()
def dial_metric(pattern):
    return float(re.search(pattern, appearance).group(1))

horizontal = 52 * dial_metric(r"horizontal = heightDp \* ([\d.]+)f")
vertical = 52 * dial_metric(r"vertical = heightDp \* ([\d.]+)f")
cell_height = 52 - vertical * 2
cell_width = (125 - horizontal * 2) / 2
arc_size = dial_metric(r"arcSize = ([\d.]+)f \*") * min(cell_width, cell_height)
content = dial_nodes["dial_content"]
for edge, padding in (("Start", horizontal), ("End", horizontal), ("Top", vertical), ("Bottom", vertical)):
    content.set(android + "padding" + edge, f"{padding:g}dp")

aapt = "{http://schemas.android.com/aapt}"
ET.register_namespace("aapt", aapt[1:-1])
for name, fraction in (("track", "1.0"), ("primary", "0.76"), ("secondary", "0.75")):
    vector = ET.parse(layouts.parent / "drawable/widget_dial_preview_track.xml").getroot()
    vector.set(android + "height", "138dp")
    vector.set(android + "viewportHeight", "138")
    path = vector.find("path")
    path.set(android + "trimPathEnd", fraction)
    if name != "track":
        path.attrib.pop(android + "strokeColor")
        color = ET.SubElement(path, aapt + "attr", {"name": "android:strokeColor"})
        ET.SubElement(color, "gradient", {
            android + "startX": "14", android + "startY": "93",
            android + "endX": "69", android + "endY": "33",
            android + "startColor": "@color/widget_classic_progress_start",
            android + "endColor": "@color/widget_classic_progress_normal"})
    ET.indent(vector, space="    ")
    (layouts.parent / f"drawable/widget_oneui_preview_{name}.xml").write_text(
        output.replace("widget_material.xml", "widget_dial_preview_track.xml")
        + ET.tostring(vector, encoding="unicode") + "\n")

for section, icon, sample in (("primary", "time", "primary"), ("secondary", "calendar_week", "secondary")):
    for layer, source in (("track", "track"), ("fill", section)):
        node = dial_nodes[f"{section}_samsung_{layer}"]
        node.set(android + "layout_width", f"{arc_size:g}dp")
        node.set(android + "layout_height", f"{arc_size:g}dp")
        node.set(android + "src", f"@drawable/widget_oneui_preview_{source}")
    node = dial_nodes[f"{section}_samsung_icon"]
    icon_fraction = dial_metric(r"size\(views, ICONS\[index\], cellHeight \* ([\d.]+)f")
    node.set(android + "layout_width", f"{cell_height * icon_fraction:g}dp")
    node.set(android + "layout_height", f"{cell_height * icon_fraction:g}dp")
    node.set(android + "layout_marginTop", f"{cell_height * icon_fraction:g}dp")
    node.set(android + "src", f"@drawable/ic_oui_{icon}")
    node = dial_nodes[f"{section}_samsung_value"]
    node.set(android + "layout_width", f"{cell_width:g}dp")
    value_fraction = dial_metric(r"size\(views, VALUES\[index\], cellWidth, cellHeight \* ([\d.]+)f")
    node.set(android + "layout_height", f"{cell_height * value_fraction:g}dp")
    margin_fraction = dial_metric(r"setViewLayoutMargin\(VALUES\[index\], RemoteViews.MARGIN_TOP, cellHeight \* ([\d.]+)f")
    node.set(android + "layout_marginTop", f"{cell_height * margin_fraction:g}dp")
    text_fraction = dial_metric(r"text.setTextSize\(heightDp \* ([\d.]+)f")
    node.set(android + "textSize", f"{52 * text_fraction:g}dp")
    node.set(android + "text", f"@string/widget_sample_{sample}_value")
ET.indent(dial_root, space="    ")
(layouts / "widget_oneui_dial_preview.xml").write_text(
    output.replace("widget_material.xml", "widget_oneui_rings.xml")
    + ET.tostring(dial_root, encoding="unicode") + "\n")

# Preserve the current generic provider contract while hiding only the ColorOS picker entry.
providers = layouts.parent / "xml"
dial = (providers / "codex_dial_widget_info.xml").read_text()
def hidden_features(match):
    features = match.group(1).split("|")
    if "hide_from_picker" not in features:
        features.append("hide_from_picker")
    return 'android:widgetFeatures="' + "|".join(filter(None, features)) + '"'

dial, count = re.subn(r'android:widgetFeatures="([^"]*)"', hidden_features, dial)
assert count == 1, "The generic dial provider must declare widgetFeatures once"
declaration, body = dial.split("\n", 1)
provider_header = ('<!-- GENERATED by android/tools/widget-card-shadow.sh from '
                   'codex_dial_widget_info.xml. Do not edit. -->\n')
(providers / "codex_dial_widget_hidden_info.xml").write_text(
    declaration + "\n" + provider_header + body)
PY
