#!/usr/bin/env bash
# Regenerates the transparent-background twins of the home widget layouts:
#   widget_card.xml     -> widget_card_shadow.xml     (WidgetCardText -> WidgetCardShadow)
#   widget_material.xml -> widget_material_shadow.xml (WidgetMaterialHeader -> ...HeaderShadow)
# RemoteViews cannot change a TextView's shadow at runtime, so each twin swaps the text styles
# for ones that add a shadow.
set -euo pipefail
LAYOUT="$(cd "$(dirname "$0")/.." && pwd)/app/src/main/res/layout"

twin() {
  local source="$1" target="$2" from="$3" to="$4"
  {
    printf '<?xml version="1.0" encoding="utf-8"?>\n'
    printf '<!-- GENERATED by android/tools/widget-card-shadow.sh from %s. Do not edit. -->\n' \
      "$source"
    sed -e '1d' -e "s|@style/${from}\\.|@style/${to}.|g" "$LAYOUT/$source"
  } > "$LAYOUT/$target"
}

twin widget_card.xml widget_card_shadow.xml WidgetCardText WidgetCardShadow
twin widget_material.xml widget_material_shadow.xml WidgetMaterialHeader WidgetMaterialHeaderShadow
